### PR TITLE
Classloader updates

### LINKED ISSUE #23769: WebappClassLoader creates duplicit class definitions in clearReferencesJdbc
See org.glassfish.main.extras.embedded.all.StartupTest log. Same stacktrace is visible also on other places. It will need some investigation, the clearReferencesJdbc is really suspicious implementation and looks like some workaround of some historical bug.

```
Jan 22, 2022 11:57:20 AM com.sun.enterprise.v3.server.AppServerStartup$MasterRunLevelListener onError
WARNING: An error occured when the system was coming down
MultiException stack 1 of 1
java.lang.LinkageError: loader org.glassfish.web.loader.WebappClassLoader @5d2e65bd attempted duplicate class definition for org.glassfish.web.loader.JdbcLeakPrevention. (org.glassfish.web.loader.JdbcLeakPrevention is in unnamed module of loader org.glassfish.web.loader.WebappClassLoader @5d2e65bd, parent loader org.glassfish.internal.api.DelegatingClassLoader @7d49a1a0)
at java.base/java.lang.ClassLoader.defineClass1(Native Method)
at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
at org.glassfish.web.loader.WebappClassLoader.clearReferencesJdbc(WebappClassLoader.java:1917)
at org.glassfish.web.loader.WebappClassLoader.clearReferences(WebappClassLoader.java:1850)
at org.glassfish.web.loader.WebappClassLoader.stop(WebappClassLoader.java:1754)
at org.glassfish.web.loader.WebappClassLoader.preDestroy(WebappClassLoader.java:1723)
at org.glassfish.internal.data.ApplicationInfo.clean(ApplicationInfo.java:445)
at com.sun.enterprise.v3.server.ApplicationLifecycle.unload(ApplicationLifecycle.java:1075)
at com.sun.enterprise.v3.server.ApplicationLifecycle.disable(ApplicationLifecycle.java:2131)
at com.sun.enterprise.v3.server.ApplicationLifecycle.disable(ApplicationLifecycle.java:93)
at com.sun.enterprise.v3.server.ApplicationLoaderService.stopApplication(ApplicationLoaderService.java:472)
at com.sun.enterprise.v3.server.ApplicationLoaderService.preDestroy(ApplicationLoaderService.java:440)
at org.jvnet.hk2.internal.ClazzCreator.preDestroyMe(ClazzCreator.java:316)
at org.jvnet.hk2.internal.ClazzCreator.dispose(ClazzCreator.java:381)
at org.jvnet.hk2.internal.SystemDescriptor.dispose(SystemDescriptor.java:521)
at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.destroyOne(AsyncRunLevelContext.java:403)
at org.glassfish.hk2.runlevel.RunLevelContext.destroyOne(RunLevelContext.java:81)
at org.jvnet.hk2.internal.ServiceHandleImpl.close(ServiceHandleImpl.java:166)
at org.glassfish.hk2.api.ServiceHandle.destroy(ServiceHandle.java:67)
at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$DownQueueRunner.run(CurrentTaskFuture.java:1270)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)

JdbcRuntimeExtension,  getAllSystemRAResourcesAndPools = [GlassFishConfigBean.org.glassfish.jdbc.config.JdbcResource, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcResource, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcConnectionPool, GlassFishConfigBean.org.glassfish.jdbc.config.JdbcConnectionPool]
Jan 22, 2022 11:57:20 AM com.sun.enterprise.v3.server.AppServerStartup stop
```

Another similar stacktrace:
```
12:06:08       [java] SEVERE: Exception while running a command
12:06:08       [java] java.lang.LinkageError: loader org.glassfish.web.loader.WebappClassLoader @6ed51944 attempted duplicate class definition for org.glassfish.web.loader.JdbcLeakPrevention. (org.glassfish.web.loader.JdbcLeakPrevention is in unnamed module of loader org.glassfish.web.loader.WebappClassLoader @6ed51944, parent loader org.glassfish.javaee.full.deployment.EarClassLoader @6caa4dc5)
12:06:08       [java] 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
12:06:08       [java] 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
12:06:08       [java] 	at org.glassfish.web.loader.WebappClassLoader.clearReferencesJdbc(WebappClassLoader.java:1792)
12:06:08       [java] 	at org.glassfish.web.loader.WebappClassLoader.clearReferences(WebappClassLoader.java:1726)
12:06:08       [java] 	at org.glassfish.web.loader.WebappClassLoader.stop(WebappClassLoader.java:1632)
12:06:08       [java] 	at org.glassfish.web.loader.WebappClassLoader.preDestroy(WebappClassLoader.java:1609)
12:06:08       [java] 	at org.glassfish.internal.data.ApplicationInfo.clean(ApplicationInfo.java:478)
12:06:08       [java] 	at com.sun.enterprise.v3.server.ApplicationLifecycle.unload(ApplicationLifecycle.java:1123)
12:06:08       [java] 	at com.sun.enterprise.v3.server.ApplicationLifecycle.undeploy(ApplicationLifecycle.java:1152)
12:06:08       [java] 	at org.glassfish.deployment.admin.UndeployCommand.execute(UndeployCommand.java:391)
12:06:08       [java] 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:529)
12:06:08       [java] 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:525)
12:06:08       [java] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
12:06:08       [java] 	at java.base/javax.security.auth.Subject.doAs(Subject.java:365)
12:06:08       [java] 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:524)
12:06:08       [java] 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:555)
12:06:08       [java] 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:547)
12:06:08       [java] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
12:06:08       [java] 	at java.base/javax.security.auth.Subject.doAs(Subject.java:365)
12:06:08       [java] 	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:546)
12:06:08       [java] 	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1456)
12:06:08       [java] 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1825)
12:06:08       [java] 	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1701)
12:06:08       [java] 	at com.sun.enterprise.admin.cli.embeddable.CommandExecutorImpl.executeCommand(CommandExecutorImpl.java:142)
12:06:08       [java] 	at com.sun.enterprise.admin.cli.embeddable.DeployerImpl.undeploy(DeployerImpl.java:136)
12:06:08       [java] 	at org.glassfish.ejb.embedded.EJBContainerImpl.undeploy(EJBContainerImpl.java:238)
12:06:08       [java] 	at org.glassfish.ejb.embedded.EJBContainerImpl.forceClose(EJBContainerImpl.java:166)
12:06:08       [java] 	at org.glassfish.ejb.embedded.EJBContainerImpl.close(EJBContainerImpl.java:155)
12:06:08       [java] 	at com.acme.Client.test(Client.java:75)
12:06:08       [java] 	at com.acme.Client.main(Client.java:42)

```

### PR DESCRIPTION
**Pull request by dmatej**
### WHY

- GlassFish classloaders were quite obsoleted, still based on Java 1.4 features.
- Known bugs
- It was hard to read the code.
- The implementation was slow.
- Logging did not tell much.
- Tomcat WebappClassLoader sources diverged, however are somehow old too. Meanwhile GF implemented other things ....

### Fixed bugs along the path

* #23769 Obsoleted code, current JDK provides solution. JdbcLeakPrevention replaced.
* ACCAgentClassLoader implemented GlassfishUrlClassLoader which is not possible as it is used as a bootstrap classloader. Introduced in 15332ce2e69b14a910 .
* ReferenceCleaner (originally inside WebappClassLoader) did not work, now does.
  * Tried to reset enums (forbidden)
  * Tried to access fields without permission (forbidden)
  * Noisy logging when it ignored excluded fields. (removed, not interesting)

### Changes

* WebappClassLoader is now "parallel-capable". Means basically declaring that and using `getClassLoadingLock(name)` for locking.
* WebappClassLoader is stateful with an attempt to strictly control what can be called
  * URLClassLoaders are Closeable
  * originally was just started and not started, while it wasn't checked.
  * now can be NEW/RUNNING/CLOSED, however some methods can be called both when NEW and RUNNING, which is not good, but it would need much more work to simplify it (give all parameters to constructor and use the CL until it is closed).
* Using System.Logger instead of JUL.
* Removed redundant logs, added new logs, set these and watch:
    ```
    org.glassfish.web.loader.WebappClassLoader.level=FINEST
    org.glassfish.web.loader.JarFileManager.level=FINEST
    org.glassfish.web.loader.ReferenceCleaner.level=FINEST
    ```
* Several new package-visible classes split from WebappClassLoader, each responsible for some segment.
  * JarFileManager manages JAR files under classloader's control
      * synchronized blocks replaced by ReentrantReadWriteLock
      * JarFile management moved inside to a special scheduled task which closes files when they are not used. This was done also in original implementation, but managed by the StandardContext and WebappLoader.
      * JarFile instances not closed on startup "to avoid peaks" as they were immediately open again.     
      * Both period and the timeout are configurable by the JVM option. Original timeout was 90 seconds, now period is 15 , timeout 60 seconds.
  * ReferenceCleaner serves to resolve possible CL leaks. If there are ThreadLocal values forgotten, it should set them to null, static fields, etc. The implementation was already there, but did not work. 
  * RepositoryManager for work with repositories. Quite simple, but maybe in next iteration we could make it yet faster ;-)
* setJarPath removed - now the CL authoritatively defines the path; the path is hardcoded on several places and must not be changed.
* WebappLoader.createClassLoader doesn't start the classloader. The start split to own method. This makes also more visible the trick in the child ...
* 

### Performance

* Currently I don't have a JMH test with a large application, but tests we have are bit faster. It should depend on hardware, from my experience Intels don't have issues with synchronizations, but sparcs had. Not sure with current ARMs etc. Would be nice if someone cloud test it ... or if I would find time :-)

### CODE REVIEW

File: appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/acc/ACCClassLoader.java [hunk 1]
```diff
@@ -187,27 +181,15 @@ private Class<?> findClassUnshadowed(String name) throws ClassNotFoundException
...
-            byte[] buffer = new byte[8196];
-            int bytesRead;
-            while ((bytesRead = is.read(buffer)) != -1) {
-                baos.write(buffer, 0, bytesRead);
+        try (InputStream is = getResourceAsStream(resourceName)) {
+            if (is == null) {
+                throw new ClassNotFoundException(className);
             }
+            ByteArrayOutputStream baos = new ByteArrayOutputStream();
+            FileUtils.copy(is, baos, is.available());
```
Comment (BalusC) [inline appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/acc/ACCClassLoader.java:189]: 3rd argument represents hopefully the buffer size not the size to copy? (this FileUtils doesn't seem to be from Apache Commons so I couldn't verify).

Comment (dmatej) [reply appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/acc/ACCClassLoader.java:189]: FileUtils attracted my attention in my second workspace, here it uses NIO and the third is used as a size.
`        outChannel.transferFrom(inChannel, 0, size);`

>  The maximum number of bytes to be transferred; must be non-negative

Maybe would be better to simply use Long.MAX_VALUE ...?

File: appserver/web/war-util/src/main/java/org/glassfish/web/loader/RepositoryManager.java [hunk 2]
```diff
@@ -0,0 +1,113 @@
...
+
+    @Override
+    public void close() throws IOException {
+        repositories.clear();
+    }
+
+    private static class Repository {
+
+        public String name;
+        public File directory;
```
Comment (BalusC) [inline appserver/web/war-util/src/main/java/org/glassfish/web/loader/RepositoryManager.java:83]: I would have made these `final` for clarity.

File: appserver/web/war-util/src/main/java/org/glassfish/web/loader/RepositoryManager.java [hunk 3]
```diff
@@ -0,0 +1,113 @@
...
+        @Override
+        public String toString() {
+            return name;
+        }
+    }
+
+    static class RepositoryResource {
+
+        public String name;
+        public File file;
```
Comment (BalusC) [inline appserver/web/war-util/src/main/java/org/glassfish/web/loader/RepositoryManager.java:100]: I would have made these `final` for clarity.

File: appserver/web/war-util/src/main/java/org/glassfish/web/loader/ResourceEntry.java [hunk 4]
```diff
@@ -38,40 +48,117 @@ public class ResourceEntry {
...
+
+
+    /**
+     * Use this constructor if codebase and source are the same.
+     *
+     * @param url resource location
+     */
+    ResourceEntry(URL url) {
+        codeBase = url;
+        source = url;
```
Comment (BalusC) [inline appserver/web/war-util/src/main/java/org/glassfish/web/loader/ResourceEntry.java:102]: I'd have used `this(url, url)`.

File: appserver/web/war-util/src/main/java/org/glassfish/web/loader/ResourceEntry.java [hunk 5]
```diff
@@ -38,40 +48,117 @@ public class ResourceEntry {
...
+    }
+
+
+    /**
+     * @param codeBase
+     * @param source {@link URL} of the entry source
+     */
+    ResourceEntry(URL codeBase, URL source) {
+        this.codeBase = codeBase;
+        this.source = source;
```
Comment (BalusC) [inline appserver/web/war-util/src/main/java/org/glassfish/web/loader/ResourceEntry.java:112]: These two props should probably be marked `final`?

File: appserver/web/war-util/src/main/java/org/glassfish/web/loader/JarFileManager.java [hunk 6]
```diff
@@ -0,0 +1,362 @@
...
+import java.util.concurrent.locks.ReadWriteLock;
+import java.util.concurrent.locks.ReentrantReadWriteLock;
+import java.util.jar.JarEntry;
+import java.util.jar.JarFile;
+
+import static java.lang.System.Logger.Level.DEBUG;
+import static java.lang.System.Logger.Level.TRACE;
+import static java.lang.System.Logger.Level.WARNING;
+import static java.util.concurrent.Executors.newScheduledThreadPool;
+import static org.glassfish.web.loader.LogFacade.getString;
```
Comment (BalusC) [inline appserver/web/war-util/src/main/java/org/glassfish/web/loader/JarFileManager.java:46]: Static import lines should be in top.

File: nucleus/deployment/common/src/main/java/org/glassfish/deployment/common/DeploymentContextImpl.java [hunk 7]
```diff
@@ -58,7 +53,12 @@
 import org.glassfish.logging.annotation.LogMessagesResourceBundle;
 import org.glassfish.logging.annotation.LoggerInfo;
 
-import com.sun.enterprise.util.LocalStringManagerImpl;
+import static com.sun.enterprise.config.serverbeans.ServerTags.IS_COMPOSITE;
+import static com.sun.enterprise.util.io.FileUtils.whack;
+import static java.lang.Boolean.FALSE;
+import static java.lang.Boolean.TRUE;
+import static java.util.logging.Level.FINE;
+import static java.util.logging.Level.FINEST;
```
Comment (BalusC) [inline nucleus/deployment/common/src/main/java/org/glassfish/deployment/common/DeploymentContextImpl.java:61]: Static import lines should remain in top.

File: appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/acc/ACCClassLoader.java (hunk 1 above)
Comment (BalusC) [reply appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/acc/ACCClassLoader.java:189]: Probably.

This just caught my attention because `is.available()` ranks among the top of beginner's misunderstandings.

File: appserver/web/war-util/src/main/java/org/glassfish/web/loader/ResourceEntry.java (hunk 5 above)
Comment (dmatej) [reply appserver/web/war-util/src/main/java/org/glassfish/web/loader/ResourceEntry.java:112]: Nope, this part is ugly (still as in original). See javadocs; some attributes are reset when the class is loaded.
Perhaps would be better to have three types of entries: UnloadedClass, LoadedClass and Resource, but finally I stopped here. It would not resolve much, maybe objects would be bit smaller ... maybe we could separate classes and resources, hmm ... maybe next time :-)

File: appserver/web/war-util/src/main/java/org/glassfish/web/loader/JarFileManager.java (hunk 6 above)
Comment (dmatej) [reply appserver/web/war-util/src/main/java/org/glassfish/web/loader/JarFileManager.java:46]: > Static import lines should be in top.

This is not defined on GF yet, most classes have them closer to the impl (I prefer this), less at the top and some in between (which is the most ugly).

Comment (BalusC) [reply appserver/web/war-util/src/main/java/org/glassfish/web/loader/JarFileManager.java:46]: It violates standard conventions and default rules of a lot of static code analyzers (sonar, checkstyle, etc).

File: appserver/web/war-util/src/main/java/org/glassfish/web/loader/ResourceEntry.java (hunk 5 above)
Comment (BalusC) [reply appserver/web/war-util/src/main/java/org/glassfish/web/loader/ResourceEntry.java:112]: Ew.

File: appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/acc/ACCClassLoader.java (hunk 1 above)
Comment (dmatej) [reply appserver/appclient/client/acc/src/main/java/org/glassfish/appclient/client/acc/ACCClassLoader.java:189]: To summarize: 
* in.available is correct here, because the input is a file and the third argument is a max count of bytes to copy.
* In next PR I will review FileUtils and document these methods, and probably explicitly warn to avoid using Long.MAX_VALUE, and also add loop to be sure we read all we expected, because based on FileChannel javadoc it is not guaranteed to be done in a single step.

File: appserver/web/war-util/src/main/java/org/glassfish/web/loader/JarFileManager.java (hunk 6 above)
Comment (dmatej) [reply appserver/web/war-util/src/main/java/org/glassfish/web/loader/JarFileManager.java:46]: I believe that depends on configuration, there is no such global standard.

I use SonarQube and this is not seen as violation. I even tried to find such rule, but to my surprise I couldn't. I know it is supported in checkstyle and I too thought it is in SonarQube too.

Btw pretty much work to do with GF. I couldn't run it for a while, because Sonar analysis crashes for OOME now :-(
https://sonarcloud.io/project/overview?id=dmatej_glassfish

Comment (BalusC) [reply appserver/web/war-util/src/main/java/org/glassfish/web/loader/JarFileManager.java:46]: Okay.

Comment (dmatej) [reply appserver/web/war-util/src/main/java/org/glassfish/web/loader/JarFileManager.java:46]: To avoid future discussions and conflicts I started trivial survey ... at least it could be representative between friends of GlassFish :-)
Based on that I will probably introduce rule in Checkstyle and fix all classes.
https://twitter.com/dmatej/status/1614963057842688000

File: appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java [hunk 8]
```diff
@@ -179,7 +179,7 @@ public class WebappClassLoader extends GlassfishUrlClassLoader
      * Use this variable to invoke the security manager when a resource is
      * loaded by this classloader.
      */
-    private final boolean packageDefinitionEnabled = System.getProperty("package.definition") != null;
+    private final boolean packageDefinitionEnabled = Boolean.getBoolean("package.definition");
```
Comment (hs536) [inline appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java]: Isn't the value obtained using "package.definition" a list of package names, not a boolean string?

Comment (dmatej) [reply appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java]: Nice catch, I tried to search the string and it seems to me it is even worse for a long time ... the property is set by catalina not to System properties, but via java.security.Security.setProperty. So this was always false.

Comment (pzygielo) [reply appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java]: Nice finding. I believe it deserves separate issue, that could be solved separately in dedicated PR.

Comment (dmatej) [reply appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java]: I brought back the original System.getProperty. Even if it is not probably worth of merging to older branches and SecurityManager will die soon, GF should be correct at the moment, so after merging this I can create another tiny PR :)

**Review by hs536 — APPROVED** [review]

File: appserver/web/war-util/src/main/java/com/sun/enterprise/glassfish/web/WarHandler.java [hunk 9]
```diff
@@ -263,10 +262,10 @@ protected void configureLoaderProperties(WebappClassLoader cloader, WebXmlParser
                     // support exploded jar file
                     cloader.addRepository("WEB-INF/lib/" + file.getName() + "/", file);
                 } else {
-                    cloader.addJar(file.getPath().substring(baseFileLen), new JarFile(file), file);
+                    cloader.addJar(file.getPath().substring(baseFileLen), file);
                 }
             } catch (final Exception e) {
-                // Catch and ignore any exception in case the JAR file is empty.
+                LOG.log(Level.FINEST, "Could not add file " + file, e);
```
Comment (arjantijms) [inline appserver/web/war-util/src/main/java/com/sun/enterprise/glassfish/web/WarHandler.java:268]: No need to change, but just a remark: many places use a static import for FINEST.

File: appserver/web/war-util/src/main/java/org/glassfish/web/loader/JarFileManager.java [hunk 10]
```diff
@@ -0,0 +1,362 @@
...
+    void closeJarFiles() {
+        LOG.log(DEBUG, "closeJarFiles()");
+        Lock writeLock = lock.writeLock();
+        try {
+            writeLock.lock();
+            lastJarFileAccess = 0L;
+            closeJarFiles(files);
+        } finally {
+            // No need to interrupt, just cancel next executions
+            this.unusedJarsCheck.cancel(false);
```
Comment (arjantijms) [inline appserver/web/war-util/src/main/java/org/glassfish/web/loader/JarFileManager.java:185]: > this.unusedJarsCheck

Is there another "unusedJarsCheck" in scope that would be invoked otherwise?

**Review by arjantijms — APPROVED** [review]

File: appserver/web/war-util/src/main/java/com/sun/enterprise/glassfish/web/WarHandler.java (hunk 9 above)
Comment (dmatej) [reply appserver/web/war-util/src/main/java/com/sun/enterprise/glassfish/web/WarHandler.java:268]: True, but not in WarHandler, I checked it now for sure. I tried to limit changes outside of loader, despite I think there is one or two classes where I "failed" and committed some eclipse autosave changes (foreach, override, braces).

**Review by BalusC — APPROVED** [review]
