### PR TITLE
Fix #25216 Redirection does not work after session timeout in Admin Console

### LINKED ISSUE #25216: Redirection does not work after session timeout in Admin Console
## Environment Details

* GlassFish Version (and build number): GlassFish 7.0.19
* JDK version: OpenJDK 21.0.4
* OS: Red Hat Enterprise Linux 8.6
* Database: none

----------

## Problem Description

After session timeout in the Admin Console, the page only containing "class jakarta.faces.application.ViewExpiredException" is shown, and the web browser is not redirected to the home page or the login page.

gui-viewexpiredexception

This behavior is reproduced in GlassFish 7 or later.
It is expected that the web browser is redirected to the home page or the login page as in GlassFish 6 or earlier.

## Steps to reproduce

This is reproduced when a button triggering Ajax communication is clicked after session timeout.

1.  Run the following commands to set the admin session timeout to 1 minute.
    *  `asadmin set server.admin-service.das-config.admin-session-timeout-in-minutes=1`
    *  `asadmin stop-domain`
    *  `asadmin start-domain`
2.  Open the Admin Console in the web browser.
3.  Open the "Clusters" page and wait more than 1 minute.
4.  Click the "New" button.

## Impact of Issue

It is an incompatibility with GlassFish 6 or earlier.

### PR DESCRIPTION
**Pull request by tnagao7**
Fixes #25216 .

This fix adds an exception handler for the Admin Console to handle `jakarta.faces.application.ViewExpiredException`.
For Ajax requests, since forwarding/redirection methods of JSF do not work as expected, this fix uses redirection by `windows.location.href` as workaround.

### CODE REVIEW

File: appserver/admingui/war/src/main/java/org/glassfish/admingui/common/AdminGuiExceptionHandler.java [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+            if (eventContext.getException() instanceof ViewExpiredException) {
+                try {
+                    FacesContext facesContext = FacesContext.getCurrentInstance();
+                    if (facesContext == null) {
+                        continue;
+                    }
+                    if (facesContext.getPartialViewContext().isAjaxRequest()) {
+                        facesContext.getExternalContext().getResponseOutputWriter().write(
+                                "<script type='text/javascript'>"
+                                        + "window.location.href = '" + facesContext.getExternalContext().getRequestContextPath() + "/';"
```
Comment (OndroMih) [inline appserver/admingui/war/src/main/java/org/glassfish/admingui/common/AdminGuiExceptionHandler.java:49]: This can be stored in a variable and reused on line 53.

**Review by OndroMih — APPROVED** [review]

File: appserver/admingui/war/src/main/java/org/glassfish/admingui/common/AdminGuiExceptionHandler.java (hunk 1 above)
Comment (tnagao7) [reply appserver/admingui/war/src/main/java/org/glassfish/admingui/common/AdminGuiExceptionHandler.java]: I've corrected it.

**Review by dmatej — APPROVED** [review]
