### PR TITLE
Try to eager load Servlets at startup.

### LINKED ISSUE #23961: CDI Test failures with GlassFish 7
Running the CDI TCK (using the runner in GlassFish) there are 11 failures as of today:

[ERROR] Failures: 

- [x]   EjbInjectionTest>Arquillian.run:138->testPassivationOfEjbs:70 » EJB java.rmi.RemoteException: CORBA BAD_OPERATION 0 No; nested exception is: 
	org.omg.CORBA.BAD_OPERATION: The delegate has not been set!  vmcid: 0x0  minor code: 0  completed: No
- [x]    AmbiguousInjectionIntoNonContextualComponentTest>Arquillian.arquillianBeforeClass:99 » Runtime Expected exception of type jakarta.enterprise.inject.spi.DeploymentException during deployment of _DEFAULT_, but no exception was thrown.
- [x]   UnsatisfiedInjectionIntoNonContextualComponentTest>Arquillian.arquillianBeforeClass:99 » Runtime Expected exception of type jakarta.enterprise.inject.spi.DeploymentException during deployment of _DEFAULT_, but no exception was thrown.
- [x]    InjectionPointTest>Arquillian.arquillianBeforeClass:99 » Runtime Expected exception of type jakarta.enterprise.inject.spi.DefinitionException during deployment of _DEFAULT_, but no exception was thrown.
- [x]    CDIProviderInitTest>Arquillian.run:138->testAccessingBeanManager:103 expected [0] but found [1]
- [x]    CDIProviderRuntimeTest>Arquillian.run:138->testGetBeanManager:76 expected [1] but found [0]
- [x]    CDIProviderRuntimeTest>Arquillian.run:138->testLookup:90 » UnsatisfiedResolution WELD-001334: Unsatisfied dependencies for type Bravo with qualifiers  

Fixed by Weld update:

- [x]   ContainerLifeCycleEventRuntimeInvocationTest>Arquillian.run:138->testAfterBeanDiscoveryEventFails:224 » NullPointer
- [x]   ContainerLifeCycleEventRuntimeInvocationTest>Arquillian.run:138->testAfterBeanDiscoveryEventFails:224 » NullPointer

See https://github.com/jakartaee/cdi/issues/624#issuecomment-1149357201

Fixed by CDI TCK update:

- [x]   PersistenceContextInjectionTest>Arquillian.run:138->testBeanTypesAndBindingTypesOfPersistenceContext:105
- [x]   PersistenceContextInjectionTest>Arquillian.run:138->testBeanTypesOfPersistenceUnit:116

See https://github.com/jakartaee/cdi-tck/issues/380

```
[ERROR] Tests run: 1837, Failures: 11, Errors: 0, Skipped: 6
```

Tests can be run from `[glassfish]/appserver/tests/tck/cdi` using:

`mvn clean install`

Individual tests can be run via

`mvn clean install -Dit.test=ExcludeFiltersTest#testExcludeSystemPropertyActivator`

Tests can be debugged via:

`mvn clean install -Dit.test=ExcludeFiltersTest#testExcludeSystemPropertyActivator -Dglassfish.suspend`

### PR DESCRIPTION
**Pull request by arjantijms**
This will trigger all the required CDI events, with as side-effect that
we also created the Servlet in advance.

According to the Servlet spec, this is allowed, and the Servlet TCK
indeed passes with this change.

Signed-off-by: Arjan Tijms <arjan.tijms@gmail.com>

### CODE REVIEW

File: appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContext.java [hunk 1]
```diff
@@ -4977,37 +4977,58 @@ public boolean alternateResourcesStop() {
...
+
         for (Container aChildren : children) {
             Wrapper wrapper = (Wrapper) aChildren;
+
             int loadOnStartup = wrapper.getLoadOnStartup();
             if (loadOnStartup < 0) {
-                continue;
+                nonLoadOnStartupServlets.add(wrapper);
+            } else {
+                loadOnStartupServlets.computeIfAbsent(loadOnStartup, e -> new ArrayList<>())
```
Comment (pzygielo) [inline appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContext.java:4990]:
```suggestion
                loadOnStartupServlets.computeIfAbsent(loadOnStartup, ArrayList::new)
```

Comment (arjantijms) [reply appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContext.java:4990]: I think arraylist::new will not work, as the key will be input into the ctor. With the key being an integer and the ctor setting the size, they will cause an out of memory with the huge key values being used.

Comment (dmatej) [reply appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContext.java:4990]: Wow, Arjan is right, I had the same idea, we discussed it in a chat and I started googling:
https://community.sonarsource.com/t/java-bug-using-collectors-tomap-with-arraylist-new/7661

File: appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContext.java [hunk 2]
```diff
@@ -4977,37 +4977,58 @@ public boolean alternateResourcesStop() {
...
+        }
+
+        if (Boolean.parseBoolean(System.getProperty("glassfish.try.preload.servlets", "true"))) {
+            // Also load the other servlets, which is one way to pass the CDI TCK, specifically
+            // ContainerEventTest#testProcessInjectionTargetEventFiredForServlet and adhere to the rule
+            // that injection points for Servlets have to be processed during start.
+            for (Wrapper wrapper : nonLoadOnStartupServlets) {
+                try {
+                    wrapper.tryLoad();
+                } catch (Throwable t) {
```
Comment (dmatej) [inline appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContext.java:5027]: One day I will remove all these dangerous "catch-all" blocks. ;-)

**Review by dmatej — APPROVED** [review]

File: appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContext.java (hunk 1 above)
Comment (pzygielo) [reply appserver/web/web-core/src/main/java/org/apache/catalina/core/StandardContext.java:4990]: I'm happy to learn it now and not from the GF bug :smile:
