### PR TITLE
Try the application classloader to restore the Principal for HA.

### LINKED ISSUE #24752: HA single sign on can't restore custom Principal from application
If an authentication mechanism sets a custom principal where the class resides within the application archive, then this principal fails to deserialise an another node when clustering and HASingleSingOn is used.

The problem seems to be that the HASingleSingOn valve (which restores the principal) runs before the valve that sets the context class loader to the one that knows about the application provided classes. Hence, the class definition can't be found.

### PR DESCRIPTION
**Pull request by arjantijms**
Fixes #24752 

This allows a custom Principal to be used that's defined by the application (the .class file resides in a .war).

The application classloader is tried last so that the existing behaviour is preserved as much as possible.

### CODE REVIEW

File: appserver/web/web-ha/src/main/java/org/glassfish/web/ha/authenticator/HASingleSignOnEntry.java [hunk 1]
```diff
@@ -180,7 +183,25 @@ private Principal parse(byte[] pbytes) {
...
+                return (Principal) ois.readObject();
+            }
+
+            try {
+                return (Principal) ois.readObject();
+            }
+            catch (ClassNotFoundException e) {
+                closeSafely(bis);
+                closeSafely(ois);
+                closeSafely(ois);
```
Comment (hs536) [inline appserver/web/web-ha/src/main/java/org/glassfish/web/ha/authenticator/HASingleSignOnEntry.java:197]: `ois` is double-closed here, shouldn't it be `bais`?

Comment (arjantijms) [reply appserver/web/web-ha/src/main/java/org/glassfish/web/ha/authenticator/HASingleSignOnEntry.java]: That was a typo indeed. I wonder if those inner streams really need to be closed explicitly. Specially closing the byte array stream doesn't do anything really, and the outer one should propagate to the inner ones anyway.

But I wanted, for now, to keep the code as close as possible to the original.

**Review by avpinchuk — APPROVED** [review]
