### PR TITLE
Fix #25288 asadmin delete-log-levels command fails if the --target option is specified

### LINKED ISSUE #25288: asadmin delete-log-levels command fails if the --target option is specified
## Environment Details
* GlassFish Version (and build number): Eclipse GlassFish 7.0.20
* JDK version: OpenJDK 21.0.3
* OS: Red Hat Enterprise Linux 8.6
* Database: none

----------

## Problem Description

If the `--target` option is specified, the `asadmin delete-log-levels` command fails to delete log levels of the specified target.

```
$ asadmin list-log-levels cluster1 | grep my.logger
 my.logger       <FINE>
    
$ asadmin delete-log-levels --target cluster1 my.logger
remote failure: An error occurred during replication
Failure: Command delete-log-levels failed on server instance instance1: remote failure: Could not delete logger levels for cluster1.
Command delete-log-levels failed.
```

## Steps to reproduce

Execute the following command lines:

```
asadmin create-cluster cluster1
asadmin create-local-instance --cluster cluster1 instance1
asadmin set-log-levels --target cluster1 my.logger=FINE
asadmin start-cluster cluster1
asadmin delete-log-levels --target cluster1 my.logger
```

## Impact of Issue
Cannot delete log levels of the specified target.

### PR DESCRIPTION
**Pull request by tnagao7**
Fixes #25288.

Fixes the `LoggingConfigImpl#deleteLoggingProperties` method to handle the `target` argument.

### CODE REVIEW

File: nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java [hunk 1]
```diff
@@ -385,7 +385,7 @@ public synchronized Map<String, String> deleteLoggingProperties(final Collection
         LOG.log(Level.INFO, "deleteLoggingProperties(properties={0})", properties);
         loadLoggingProperties();
         remove(properties);
-        rewritePropertiesFileAndNotifyMonitoring();
+        rewritePropertiesFileAndNotifyMonitoring("");
```
Comment (dmatej) [inline nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java:388]: `null` would be better

File: nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java [hunk 2]
```diff
@@ -394,20 +394,25 @@ public synchronized Map<String, String> deleteLoggingProperties(final Collection
...
     private void remove(final Collection<String> keys) {
         final Consumer<String> toRealKeyAndDelete = k -> props.remove(LoggingXMLNames.xmltoPropsMap.getOrDefault(k, k));
         keys.forEach(toRealKeyAndDelete);
     }
 
-    private void rewritePropertiesFileAndNotifyMonitoring() throws IOException {
+    private void rewritePropertiesFileAndNotifyMonitoring(final String targetConfigName) throws IOException {
         LOG.finest("rewritePropertiesFileAndNotifyMonitoring");
-        File file = getLoggingPropertiesFile();
+        File file = null;
```
Comment (dmatej) [inline nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java:410]: You can make it final and remove the redundant null assignment as you always set it in `if` or in `else` block.

Comment (tnagao7) [reply nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java]: I have modified the code.

File: nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java (hunk 1 above)
Comment (tnagao7) [reply nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java:388]: Thank you for your suggestion. 
But existing code uses  `""` instead of `null` as below, and using `""` and `null` mixedly would not be desirable...

https://github.com/eclipse-ee4j/glassfish/blob/858cfe603f66c1e2c5b4d9cbf10baa9da01ac3e7/nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java#L235

https://github.com/eclipse-ee4j/glassfish/blob/858cfe603f66c1e2c5b4d9cbf10baa9da01ac3e7/nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java#L301

If we want to refactor this code, method overloading (i.e. defining `rewritePropertiesFileAndNotifyMonitoring()` and `closePropFile()` without arguments) would be better rather than using `""` and `null`.
Since doing such refactoring in the current pull request obscures the essense of the bug fix, I think we can do it in another pull request if needed.

Comment (dmatej) [reply nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java:388]: I would just replace all those empty strings with `null` (and in the future this class should never get an empty string target, it should be resolved when parsing the user input). Adding overloaded methods doesn't bring a value in private methods. Refactoring is ok if you put it to separate commit from the fix.

Additional PR means more work to each of us and waiting on CI ;-)

**Review by dmatej — APPROVED** [review]

File: nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java (hunk 1 above)
Comment (tnagao7) [reply nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java]: Okay, I've modified the code to use `null` instead of `""`.

**Review by dmatej — APPROVED** [review]
