### PR TITLE
Fixed PowerShell script on Windows and removed bat file

### LINKED ISSUE #25429: GlassFish doesn't start on Windows if running scripts is disabled
GlassFish version: 7.0.23
OS: Windows (any supported version)

When executing powershell scripts is disabled on Windows, execution of asadmin start-domain will give the following error:

```
[INFO] Resolved container artifact org.codehaus.cargo:cargo-core-container-glassfish:jar:1.10.15 for container glassfish7x
[INFO] Parsed GlassFish version = [7.0.23]
[INFO] GlassFish 7.0.23 starting...
[INFO] Executing: powershell.exe -File "C:\GitHub\cargotracker\target\cargo\configurations\glassfish7x\cargo-domain\config\gfstart.ps1" -BatchFilePath "C:\GitHub\cargotracker\target\cargo\configurations\glassfish7x\cargo-domain\config\gfstart.bat"
[INFO] Please look at the server log for more details...
[INFO] Waiting for cargo-domain to start
[INFO] Waiting finished after 371 ms.
[INFO] Error starting domain cargo-domain.
[INFO] The server exited prematurely with exit code 1.
[INFO] Before it died, it produced the following output:
[INFO]
[INFO] File C:\GitHub\cargotracker\target\cargo\configurations\glassfish7x\cargo-domain\config\gfstart.ps1 cannot be loaded
[INFO] because running scripts is disabled on this system. For more information, see about_Execution_Policies at
[INFO] https:/go.microsoft.com/fwlink/?LinkID=135170.
[INFO]     + CategoryInfo          : SecurityError: (:) [], ParentContainsErrorRecordException
[INFO]     + FullyQualifiedErrorId : UnauthorizedAccess
[INFO]  Error starting domain cargo-domain.
[INFO] The server exited prematurely with exit code 1.
[INFO] Before it died, it produced the following output:
[INFO]
[INFO] File C:\GitHub\cargotracker\target\cargo\configurations\glassfish7x\cargo-domain\config\gfstart.ps1 cannot be loaded
[INFO] because running scripts is disabled on this system. For more information, see about_Execution_Policies at
[INFO] https:/go.microsoft.com/fwlink/?LinkID=135170.
[INFO]     + CategoryInfo          : SecurityError: (:) [], ParentContainsErrorRecordException
[INFO]     + FullyQualifiedErrorId : UnauthorizedAccess
[INFO]
[INFO] Command start-domain failed.
```

Thanks to @m-reza-rahman for reporting this.

### PR DESCRIPTION
**Pull request by dmatej**
- Fixes #25429 partially
  - It is not possible to fix ti completely.
  - We can however avoid using powershell for local execution. Windows then will kill the instance after user logs out.
  - For SSH nodes Windows kills instance immediately after SSH ends. That is why we use the Scheduler to start instance not as a child of the SSH process, windows then let them live. User needs permissions to schedule tasks and to execute powershell scripts.
- Fixes problems with spaces which BAT files cannot resolve (just strings) while PowerShell is much better in this (CSV-like array).
- Created issue #25457 to improve the documentation.
- Fixes endlocal effect in "user" bat scripts (asadmin, nadmin, appclient) which set env variables outside their own scope. See https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/setlocal for details.

### Manual Testing
* Passed `glassfish-itest-tools` tests in the project directory renamed to have spaces in name.
* Tested using **https://github.com/eclipse-ee4j/glassfish/discussions/25343** with a space in the windows node path.
   ```
   change-admin-password
   enable-secure-admin
   restart-domain
   create-node-ssh --nodehost 192.168.56.101 --installdir '/Users/vboxuser/glassfish 7' --sshuser vboxuser --sshkeyfile /home/dmatej/.ssh/id_rsa_nopassphrase --install true win2025
   create-cluster ClusterOne
   create-instance --cluster ClusterOne --node win2025 InstanceWin2025
   start-instance InstanceWin2025
   stop-instance InstanceWin2025
   start-cluster ClusterOne
   stop-instance InstanceWin2025
   ``` 
   Then I moved to the windows node running in VirtualBox - there is few unhappy surprises like firewalls interrupting connections of stopped processes, session isolation so you cannot use jcmd and ProcessBuilder to access processes by pid if they were started in different sessions, etc. However we are still able to face it.
   ```
   C:\Users\vboxuser>".\glassfish 7\glassfish\bin\asadmin" start-local-instance InstanceWin2025
   C:\Users\vboxuser>".\glassfish 7\glassfish\bin\asadmin" stop-local-instance InstanceWin2025
   ```

### Limitaions
* To use SSH Nodes on windows Server 2025 you need privileges
* Windows Server 2025 limits visible processes to current session - even jcmd executed locally cannot see JVMs started using SSH. So using start-local-instance and stop-local-instance is possible just "symmetrically", you cannot stop process by PID started via SSH. However DAS can as it uses SSH too.
* Instances started using local commands are killed once user logs off the system - with the end of the session.

### CODE REVIEW

**Review by arjantijms — APPROVED** [review]
lgtm

File: nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/IdmService.java [hunk 1]
```diff
@@ -184,6 +186,14 @@ private boolean setFromStdin() {
         } catch (Exception e) {
             logger.fine("Stdin isn't behaving, ignoring it ..." + e.getMessage());
             return false;
+        } finally {
+            try {
+                System.in.close();
```
Comment (pzygielo) [inline nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/IdmService.java:191]: I understand that
> Closing a previously closed stream has no effect.

But wouldn't `stdin` be closed already by [since now] try-with-resources with closing `br`?

> BufferedReader.close
> Closes the stream and releases any system resources associated with it

> InputStreamReader.close
> Closes the stream and releases any system resources associated with it.

Comment (pzygielo) [reply nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/IdmService.java:191]: > But wouldn't `stdin` be closed already by [since now] try-with-resources with closing `br`?

Answer is: yes, it would be closed.

I'd like to see that `finally` block to be removed.

Comment (dmatej) [reply nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/IdmService.java:191]: I would say so, but honestly I gave up after another "Cannot delete the directory" error on Windows. Maybe I made some mistake when I was testing that, like using old build, not sure now. Or maybe there was yet another change causing the problem. I will come back to this soon as I know yet about one place with similar issue.
