### PR TITLE
Generate missing config when asadmin set is called (2nd attempt)

### LINKED ISSUE #24158: Asadmin set command fails if the parent config object isn't already present
## Environment Details
* GlassFish 7.0.0-M9
* JDK version: Zulu17.36+13-CA (build 17.0.4+8-LTS)
* OS: Ubuntu 22.04.1 LTS
* Database: N/A

----------

## Problem Description

When running asadmin set command to set a dotted configuration and the parent dotted configuration doesn't exist, the set command fails to set the configuration.

## Steps to reproduce

On a fresh GlassFish installation, run:

```
 bin/asadmin set configs.config.server-config.network-config.protocols.protocol.http-listener-1.ssl.cert-nickname=s1as
```
This will fail with the following output:

```
remote failure: No configuration found for configs.config.server-config.network-config.protocols.protocol.http-listener-1.ssl
Command set failed.
```

This is because the default `domain.xml` file doesn't contain any `ssl` element for the `http-listener-1` protocol. It works for the `http-listener-2` protocol, which contains the `ssl` element.

A similar error can be reproduced in Admin Console if GlassFish is built from these branches: https://github.com/eclipse-ee4j/glassfish/issues/23782#issuecomment-1291023938. When editing the SSL tab of the http-listener-1, pressing the Save button leads to the same error and there's no way to fix this in the Admin Console.

## Impact of Issue
[//]: When editing the SSL configuration of the HTTP listener, it's not possible to save the configuration in Admin Console.

[//]: # "Please choose one each Type, Component, and Priority label"

Type:Enhancement
Component: Kernel, Admin, Admin Console

### PR DESCRIPTION
**Pull request by OndroMih**
Fixes https://github.com/eclipse-ee4j/glassfish/issues/24158. Automatically creates missing config nodes in the `set` command, if they aren't present in domain.xml.

Added tests to cover multiple scenarios:

* setting an attribute directly (this test was already present)
* setting an attribute through an alias (a different dotted name leading to the same config node)
* seting a custom property `a=b`
* setting an attribute on a node which isn't in the current configuration and which will be created before setting the attribute (this is the new feature implemented)

This is a fix of https://github.com/eclipse-ee4j/glassfish/pull/24160, which was reverted by https://github.com/eclipse-ee4j/glassfish/pull/24170 to pass the tests.

### CODE REVIEW

File: nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/SetCommand.java [hunk 1]
```diff
@@ -194,6 +194,320 @@ private String getResourceName() {
...
+            String prefix;
+            boolean lookAtSubNodes;
+            boolean applyOverrideRules;
+
+            private Map<Dom, String> findDottedNames(TreeNode[] parentNodes, String pattern) {
+                Map<Dom, String> dottedNames = new HashMap<Dom, String>();
+                this.applyOverrideRules = false;
+                if (lookAtSubNodes) {
+                    for (TreeNode parentNode : parentNodes) {
+                        dottedNames.putAll(getAllDottedNodes(parentNode.node));
```
Comment (pzygielo) [inline nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/SetCommand.java:211]: https://ci.eclipse.org/glassfish/job/glassfish_build-and-test-using-jenkinsfile/view/change-requests/job/PR-24185/2/console
```
[ERROR] /home/jenkins/agent/workspace/_test-using-jenkinsfile_PR-24185/nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/SetCommand.java:[211,44] non-static method getAllDottedNodes(org.jvnet.hk2.config.Dom) cannot be referenced from a static context
```

Comment (OndroMih) [reply nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/SetCommand.java:214]: I'm sorry, I should have checked better. I rebased against `master`, that broke my build but I forgot to rebuild again. Should be fixed by my most recent commit

**Review by dmatej — APPROVED** [review]
