### PR TITLE
Fixes issue #24849 make relevant methods synchronized in LocalTxConnectionEventListener 

### LINKED ISSUE #24849: Improve Thread safeness of LocalTxConnectionEventListener
Improve Thread safeness of LocalTxConnectionEventListener to prevent errors like:
```
Caused by: java.lang.NullPointerException: Cannot invoke "com.sun.enterprise.resource.ResourceHandle.getResourceSpec()" because "resource" is null
        at com.sun.enterprise.resource.pool.PoolManagerImpl.resourceClosed(PoolManagerImpl.java:367)
        at com.sun.enterprise.resource.listener.LocalTxConnectionEventListener.connectionClosed(LocalTxConnectionEventListener.java:58)
        at com.sun.gjc.spi.ManagedConnectionImpl.connectionClosed(ManagedConnectionImpl.java:735)
        at com.sun.gjc.spi.base.ConnectionHolder.close(ConnectionHolder.java:193)
        at com.sun.gjc.spi.jdbc40.ConnectionHolder40.close(ConnectionHolder40.java:590)
```
to improve the contents of the associatedHandles Map to be more threadsafe.

As part of the investigation of #24805 I ran into similar Payara issue: https://github.com/payara/Payara/issues/3029 which I logged in the past. This was fixed in https://github.com/payara/Payara/commit/c09e8aafd53221a918230db5d2c9c1098c5f2a76 

Fix idea:
- improve calls to "private IdentityHashMap associatedHandles;" to be more thread safe, preventing poolManager.resourceClosed(handle); to be called if another thread already updated associatedHandles.
- refactor com.sun.enterprise.resource.ConnectorXAResource.resetAssociation() logic -> so no external classes are updating associatedHandles anymore, making updating the associatedHandles the responsibility of class LocalTxConnectionEventListener

### PR DESCRIPTION
**Pull request by escay**
Make relevant methods synchronized in LocalTxConnectionEventListener and protect associatedHandles from external clear calls.

I first tried to move most of the ConnectorXAResource.resetAssociation method inside a synchronous method in the LocalTxConnectionEventListener, but that also meant two other methods from ConnectorXAResource needed to be refactored and moved into LocalTxConnectionEventListener. So I undid that and chose for cloning the map and returning a clone to make the method getAssociatedHandles thread safe. This is a different solution as used in the Payara fix I mention in the issue. But I think it is better to leave the association and disassociating of ManagedConnection logic inside the ConnectorXAResource code.

I did not add multi threading unit tests, since only the basic synchronized(this) approach is used to protect the associatedHandles map. No need to test java. I did add some basic unit test logic for the add and remove logic used by ConnectorXAResource.

### CODE REVIEW

File: appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/ConnectorXAResource.java [hunk 1]
```diff
@@ -120,7 +124,9 @@ public void end(Xid xid, int flags) throws XAException {
                 if (handle != null) { // not needed, just to be sure.
                     ManagedConnection associatedConnection = (ManagedConnection) handle.getResource();
                     associatedConnection.associateConnection(userHandle);
-                    _logger.log(FINE, "connection_sharing_reset_association", userHandle);
```
[the remark this answers is not in the document]
Comment (escay) [reply appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/ConnectorXAResource.java:123]: You mean I can remove the
if (_logger.isLoggable(FINE)) {

in both cases. I added it here, to be in sync / reflect the resetAssociation() original code which did use the if.
I will remove both ifs.

**Review by dmatej — APPROVED** [review]

File: appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/listener/LocalTxConnectionEventListener.java [hunk 2]
```diff
@@ -32,37 +32,51 @@
...
-        this.associatedHandles = new IdentityHashMap(10);
-        this.poolManager = ConnectorRuntime.getRuntime().getPoolManager();
     }
 
     @Override
-    public void connectionClosed(ConnectionEvent evt) {
+    public synchronized void connectionClosed(ConnectionEvent evt) {
         Object connectionHandle = evt.getConnectionHandle();
         ResourceHandle handle = resource;
         if (associatedHandles.containsKey(connectionHandle)) {
```
Comment (avpinchuk) [inline appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/listener/LocalTxConnectionEventListener.java:65]: Here we do two map lookups. Maybe it's better to use

```java
ResourceHande handle = associatedHandes.getOrDefault(connectionHandle, resource);
```

File: appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/listener/LocalTxConnectionEventListener.java [hunk 3]
```diff
@@ -72,12 +86,15 @@ public void connectionErrorOccurred(ConnectionEvent evt) {
      * @param evt ConnectionEvent
      */
     @Override
-    public void badConnectionClosed(ConnectionEvent evt) {
+    public synchronized void badConnectionClosed(ConnectionEvent evt) {
         Object connectionHandle = evt.getConnectionHandle();
         ResourceHandle handle = resource;
         if (associatedHandles.containsKey(connectionHandle)) {
```
Comment (avpinchuk) [inline appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/listener/LocalTxConnectionEventListener.java:92]: Here too

Comment (avpinchuk) [reply appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/listener/LocalTxConnectionEventListener.java:92]: Also, because `synchronized` is only used to guard access to the associated handles map, maybe it's better to use `ReentrantReadWriteLock` instead?

**Comment by avpinchuk** [comment]
Also, because `synchronized` is only used to guard access to the associated handles map, maybe it's better to use `ReentrantReadWriteLock` instead?

File: appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/listener/LocalTxConnectionEventListener.java (hunk 2 above)
Comment (escay) [reply appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/listener/LocalTxConnectionEventListener.java:65]: Thank you, I was not aware of this getOrDefault option on Maps.
Documentation of getOrDefault defines: "The default implementation makes no guarantees about synchronization or atomicity properties of this method." so I think the synchronization on the method is still needed.
I can make an update later today.

Comment (avpinchuk) [reply appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/listener/LocalTxConnectionEventListener.java:65]: You're right, synchronization is needed. We simply eliminate unnecessary map access.

**Comment by escay** [comment]
> Also, because `synchronized` is only used to guard access to the associated handles map, maybe it's better to use `ReentrantReadWriteLock` instead?

I cannot oversee the impact of using ReentrantReadWriteLock on only the associatedHandles. Some code like the
 `poolManager.resourceClosed(handle);` calls could also be affected by the synchronized approach. I have no easy way to test this, I know the synchronized version works for me for the last years in Payara: https://github.com/payara/Payara/commit/c09e8aafd53221a918230db5d2c9c1098c5f2a76 to avoid the exception, so I tried to stay near that solution.
 
To know for sure I think I need to have found the real cause of issue #24805 and probably also of issue  #23483 which I think could be related and run my test set many times. 
I am also looking at: 

https://github.com/eclipse-ee4j/glassfish/blob/3e5203c56e63abf68cece6ddc76cf9ffd91c3d69/appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/ConnectionPool.java#L679C1-L682C66

where I suspect resourceHandles can get mixed up, and could perhaps cause this issue as side effect.

**Review by avpinchuk — APPROVED** [review]
