### PR TITLE
#23566 Qualify calls to yield()

### LINKED ISSUE #23566: Qualify calls to "yield()"
Javadoc generation currently reports errors for this during the build:

```
org.apache.maven.reporting.MavenReportException: 
Exit code: 1 - /glassfish/nucleus/common/common-util/src/main/java/com/sun/enterprise/util/ProcessExecutor.java:645: 

error: invalid use of a restricted identifier 'yield'
                yield();
```

### PR DESCRIPTION
**Pull request by arjantijms**
Fixes #23566

Signed-off-by: arjantijms arjan.tijms@gmail.com

### CODE REVIEW

File: appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/RecoveryManager.java [hunk 1]
```diff
@@ -58,6 +52,12 @@
 import org.omg.CORBA.SystemException;
 import org.omg.CORBA.TRANSIENT;
 import org.omg.CosTransactions.Status;
+
+import com.sun.enterprise.transaction.jts.api.TransactionRecoveryFence;
```
Comment (dmatej) [inline appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/RecoveryManager.java:56]: Hmmm, I would keep simple aplhabetical ordering in imports, so we would not fight in each part again and again (here I am not a part of the fight)  :dagger:

**Review by dmatej — APPROVED** [review]

File: appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/RecoveryManager.java (hunk 1 above)
Comment (arjantijms) [reply appserver/transaction/jts/src/main/java/com/sun/jts/CosTransactions/RecoveryManager.java:56]: It's the auto-ordering of the IDE ;)
