### PR TITLE
Fix for 'WELD-001409: Ambiguous dependencies for type EntityManager' when persistence.xml contains more than one persistence-unit

### LINKED ISSUE #25934: WELD-001409: Ambiguous dependencies for type EntityManager
### GlassFish Version (and build number)

8.0.0

### JDK version

OpenJDK 21

### OS

Windows

### Database

_No response_

### Problem Description

When persistence.xml contains 2 persistence units, fatal error is occurred:
```
Error occurred during deployment: Exception while loading the app : CDI deployment failure: WELD-001409: Ambiguous dependencies for type EntityManager with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private Index.entityManager
  at Index.entityManager(Index.java:0)
  Possible dependencies:
  - Configurator Bean [class org.glassfish.cdi.persistence.PersistenceExtension, types: Object, EntityManager, qualifiers: @Any @Default @Named],
  - Configurator Bean [class org.glassfish.cdi.persistence.PersistenceExtension, types: Object, EntityManager, qualifiers: @Any @Default @Named]
. Please see server.log for more details.
```

### Steps to reproduce

create 2 persistence units in one persistence.xml  (or duplicate existing one with new name)

### Impact of Issue

_No response_

### PR DESCRIPTION
**Pull request by bvfalcon**
- Fixes #25934

### CODE REVIEW

File: appserver/web/weld-integration/src/main/java/org/glassfish/cdi/persistence/PersistenceExtension.java [hunk 1]
```diff
@@ -48,16 +48,19 @@
...
+
     public void afterBean(final @Observes AfterBeanDiscovery afterBeanDiscovery, BeanManager beanManager) {
         var container = Globals.get(InvocationManager.class)
                                   .getCurrentInvocation()
                                   .getContainer();
 
         if (container instanceof ApplicationInfo applicationInfo) {
 
-            var persistenceUnits = applicationInfo.getMetaData(PersistenceUnitsDescriptor.class);
+        	PersistenceUnitsDescriptor persistenceUnits = applicationInfo.getMetaData(PersistenceUnitsDescriptor.class);
```
Comment (pzygielo) [inline appserver/web/weld-integration/src/main/java/org/glassfish/cdi/persistence/PersistenceExtension.java]:
```
18:34:06  [INFO] There is 1 error reported by Checkstyle 12.3.1 with org/glassfish/qa/config/checkstyle/checkstyle.xml ruleset.

18:34:06  [ERROR] src/main/java/org/glassfish/cdi/persistence/PersistenceExtension.java:[60,9] (whitespace) FileTabCharacter: Line contains a tab character.
```

File: appserver/web/weld-integration/src/main/java/org/glassfish/cdi/persistence/PersistenceExtension.java [hunk 2]
```diff
@@ -48,16 +48,19 @@
...
                                   .getContainer();
 
         if (container instanceof ApplicationInfo applicationInfo) {
 
-            var persistenceUnits = applicationInfo.getMetaData(PersistenceUnitsDescriptor.class);
+            PersistenceUnitsDescriptor persistenceUnits = applicationInfo.getMetaData(PersistenceUnitsDescriptor.class);
 
-            if (persistenceUnits != null) {
+            if (persistenceUnits != null && !persistenceUnits.isEmpty()) {
+                firstPersistenceUnitDescriptor = persistenceUnits.getPersistenceUnitDescriptors().getFirst();
```
Comment (OndroMih) [inline appserver/web/weld-integration/src/main/java/org/glassfish/cdi/persistence/PersistenceExtension.java:63]: Please set `firstPersistenceUnitDescriptor = null` at the end of this method to avoid keeping it in memory if not needed anymore. The `PersistenceExtension` instance keeps in memory all the time until the app is undeloyed.

Comment (OndroMih) [reply appserver/web/weld-integration/src/main/java/org/glassfish/cdi/persistence/PersistenceExtension.java:63]: Looks good to me otherwise, thanks!

Comment (bvfalcon) [reply appserver/web/weld-integration/src/main/java/org/glassfish/cdi/persistence/PersistenceExtension.java:63]: > set firstPersistenceUnitDescriptor = null at the end of this method 

done

**Review by OndroMih — APPROVED** [review]
Thank you!

File: appserver/web/weld-integration/src/main/java/org/glassfish/cdi/persistence/GlassFish.java [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+import static java.lang.annotation.ElementType.FIELD;
+import static java.lang.annotation.ElementType.METHOD;
+import static java.lang.annotation.ElementType.PARAMETER;
+import static java.lang.annotation.ElementType.TYPE;
+import static java.lang.annotation.RetentionPolicy.RUNTIME;
+
+@Target({ TYPE, METHOD, PARAMETER, FIELD })
+@Retention(RUNTIME)
+@Qualifier
+public @interface GlassFish {
```
Comment (dmatej) [inline appserver/web/weld-integration/src/main/java/org/glassfish/cdi/persistence/GlassFish.java]: I am not sure this is a good name, as there is already a GlassFish interface with different usage and following this pattern we could create many GlassFish classes. Sure, it has different package name, but ... I don't know.

Comment (OndroMih) [reply appserver/web/weld-integration/src/main/java/org/glassfish/cdi/persistence/GlassFish.java]: You're right. Naming is difficult. This is meant to be just an internal class but it's probably good to give it a different name. Maybe `GlassFishDefaultEntityManager`?

Comment (avpinchuk) [reply appserver/web/weld-integration/src/main/java/org/glassfish/cdi/persistence/GlassFish.java]: Maybe without `Glassfish` and without default? The `@SecondaryPersistenceUnit` or `@AdditionalPersistenceUnit` seems reasonable.

Comment (pzygielo) [reply appserver/web/weld-integration/src/main/java/org/glassfish/cdi/persistence/GlassFish.java]: Does it need to be `public`?

Comment (bvfalcon) [reply appserver/web/weld-integration/src/main/java/org/glassfish/cdi/persistence/GlassFish.java]: With this new annotation will be annotated not only EntityManager -- all other beans, created by PersistenceExtension, too: EntityManagerFactory, CriteriaBuilder, Cache and several others. This new annotation will be applied to 2-nd, 3-rd and all subsequent persistence units. Therefore name `@SecondaryPersistenceUnit` seems the most reasonable.
Yes, it needs to be public: with `@Retention(RUNTIME)` bean will be processed by cdi-container and non-public `@interface` causes problems. I check it additionally with my applications on GF 8.

**Review by avpinchuk — APPROVED** [review]
LGTM

**Review by dmatej — APPROVED** [review]
