### PR TITLE
Fix for #24104 - fixed infinite loop

### LINKED ISSUE #24104: Infinite loop in CustomTokenClient
This one was catched on my build server, probably forbidden, but it should crash, not end in infinite loop.
Version: current master branch (7.0.0-SNAPSHOT)

```
"main" #1 prio=5 os_prio=0 cpu=789558.96ms elapsed=813.63s tid=0x00007f9688023b70 nid=0x126e runnable  [0x00007f968ddff000]
java.lang.Thread.State: RUNNABLE
at com.sun.enterprise.admin.servermgmt.domain.CustomTokenClient.getSubstitutableTokens(CustomTokenClient.java:114)
at com.sun.enterprise.admin.servermgmt.domain.DomainBuilder.run(DomainBuilder.java:281)
at com.sun.enterprise.admin.servermgmt.cli.CreateDomainCommand.createTheDomain(CreateDomainCommand.java:411)
at com.sun.enterprise.admin.servermgmt.cli.CreateDomainCommand.executeCommand(CreateDomainCommand.java:268)
at com.sun.enterprise.admin.cli.CLICommand.execute(CLICommand.java:291)
at com.sun.enterprise.admin.cli.AdminMain.executeCommand(AdminMain.java:304)
at com.sun.enterprise.admin.cli.AdminMain.doMain(AdminMain.java:241)
at org.glassfish.admin.cli.AsadminMain.main(AsadminMain.java:33)
```

### PR DESCRIPTION
**Pull request by dmatej**
- added escape path if it is not possible to find openable free port.
- fixes #24104

### CODE REVIEW

File: nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/domain/CustomTokenClient.java [hunk 1]
```diff
@@ -111,6 +112,9 @@ public Map<String, String> getSubstitutableTokens() throws DomainException {
                             }
                             // Find next available unused port by incrementing the port value by 1
                             while (!NetUtils.isPortFree(port) && !usedPorts.contains(port)) {
+                                if (port > NetUtils.MAX_PORT) {
+                                    throw new DomainException("No free port available or it is prohibited.");
```
Comment (pzygielo) [inline nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/domain/CustomTokenClient.java:116]: Seems that other `DomainException`s here use `_strings` to get the message.

Comment (dmatej) [reply nucleus/admin/server-mgmt/src/main/java/com/sun/enterprise/admin/servermgmt/domain/CustomTokenClient.java:116]: It just extends RepositoryException which extends java.lang.Exception, no i18n inside. The plan is to get rid all of these messages as they are pretty inconsistent and often copy pasted same to a property file and same "as a default". But that will be for another pr(s).

**Review by arjantijms — APPROVED** [review]
