### PR TITLE
Fixed asadmin get -m for monitoring

### LINKED ISSUE #25695: Fix asadmin monitoring commands
### GlassFish Version (and build number)

All versions, tested 7.0.25 and master branch

### JDK version

17

### OS

Tuxedo

### Database

Derby, Postgress

### Problem Description

The following sequence should result in printing a list of monitored values and their descriptions (in a format like usual get command). But it doesn't do anything, HOWEVER ... under some circumstances it starts working, but I could not find out what enables that.
The Admin GUI shows those data, but asadmin doesn't.

### Steps to reproduce

```
asadmin set configs.config.server-config.monitoring-service.module-monitoring-levels.jdbc-connection-pool=HIGH
asadmin set configs.config.server-config.monitoring-service.module-monitoring-levels.jvm=HIGH
asadmin start-database
asadmin ping-connection-pool DerbyPool
asadmin ping-connection-pool __TimerPool
asadmin --terse get -m 'server.resources.*'
asadmin --terse get -m '*'
```

### Impact of Issue

_No response_

### PR DESCRIPTION
**Pull request by dmatej**
- Fixes #25695 
- The plain reporter's message was lost finally; removal resolved the problem.
- added generics
- removed unused fields
- reduced visibility of fields
- I am using monitoring in another branch, so this became a blocker for me
- 7.0.25 works (mostly)

### CODE REVIEW

File: nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/MonitoringReporter.java [hunk 1]
```diff
@@ -183,49 +187,37 @@ public void execute() {
...
     private void runAggregate() {
         List<String> list = getOutputLines();
-        ActionReport aggregateReporter = null;
+        final ActionReport aggregateReporter;
         if (aggregateDataOnly) {
-            plainReporter = new PlainTextActionReporter();
-            aggregateReporter = plainReporter.addSubActionsReport();
+            aggregateReporter = reporter.addSubActionsReport();
         } else {
             aggregateReporter = reporter.addSubActionsReport();
```
Comment (avpinchuk) [inline nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/MonitoringReporter.java]: Why here the `if else` statement? Both conditions do the same assignment.

Comment (dmatej) [reply nucleus/core/kernel/src/main/java/com/sun/enterprise/v3/admin/MonitoringReporter.java]: Because originally I was trying to work on something else, thanks for noticing that!

**Review by avpinchuk — APPROVED** [review]
