### PR TITLE
Tests to verify that tasks submitted to executor during deployment are executed

### LINKED ISSUE #21087: ManagedExecutorService does not execute tasks submitted during application startup
I'm attempting to schedule a task from inside a singleton bean which is initialised at startup:

```
@Singleton
@Startup
public class StartupSingleton {
      @Resource
      ManagedExecutorService executorService;

      @PostConstruct
      public void init() {
            System.out.println("init");
            Future<?> future = executorService.submit(new Runnable() {
  public void run() {
        System.out.println("run");
  }
            });

            try {
  Thread.sleep(1000);
  if(future.isDone()) {
        future.get();
        System.out.println("ok");
  } else {
        System.out.println("not run");
  }
            } catch (Exception e) {
  e.printStackTrace();
            }
      }
}
```

I then get the following in the logs:

```
2014-06-10T15:45:07.497+0930|Info: init
2014-06-10T15:45:08.499+0930|Severe: java.util.concurrent.ExecutionException: javax.enterprise.concurrent.AbortedException: Module glassfish-executor-test is disabled
      at java.util.concurrent.FutureTask.report(FutureTask.java:122)
      at java.util.concurrent.FutureTask.get(FutureTask.java:188)
      at foo.StartupSingleton.init(StartupSingleton.java:33)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:606)
      at com.sun.ejb.containers.interceptors.BeanCallbackInterceptor.intercept(InterceptorManager.java:1035)
      at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
      at com.sun.ejb.containers.interceptors.CallbackInvocationContext.proceed(CallbackInvocationContext.java:205)
      at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:55)
      at sun.reflect.GeneratedMethodAccessor129.invoke(Unknown Source)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:606)
      at com.sun.ejb.containers.interceptors.CallbackInterceptor.intercept(InterceptorManager.java:986)
      at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
      at com.sun.ejb.containers.interceptors.CallbackInvocationContext.proceed(CallbackInvocationContext.java:205)
      at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
      at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.init(SystemInterceptorProxy.java:125)
      at sun.reflect.GeneratedMethodAccessor130.invoke(Unknown Source)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:606)
      at com.sun.ejb.containers.interceptors.CallbackInterceptor.intercept(InterceptorManager.java:986)
      at com.sun.ejb.containers.interceptors.CallbackChainImpl.invokeNext(CallbackChainImpl.java:72)
      at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:412)
      at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:375)
      at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:1949)
      at com.sun.ejb.containers.AbstractSingletonContainer.createSingletonEJB(AbstractSingletonContainer.java:475)
      at com.sun.ejb.containers.AbstractSingletonContainer.access$000(AbstractSingletonContainer.java:81)
      at com.sun.ejb.containers.AbstractSingletonContainer$SingletonContextFactory.create(AbstractSingletonContainer.java:654)
      at com.sun.ejb.containers.AbstractSingletonContainer.instantiateSingletonInstance(AbstractSingletonContainer.java:396)
      at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:219)
      at org.glassfish.ejb.startup.SingletonLifeCycleManager.initializeSingleton(SingletonLifeCycleManager.java:180)
      at org.glassfish.ejb.startup.SingletonLifeCycleManager.doStartup(SingletonLifeCycleManager.java:158)
      at org.glassfish.ejb.startup.EjbApplication.start(EjbApplication.java:166)
      at org.glassfish.internal.data.EngineRef.start(EngineRef.java:122)
      at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:291)
      at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:352)
      at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:497)
      at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:219)
      at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:491)
      at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:527)
      at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:523)
      at java.security.AccessController.doPrivileged(Native Method)
      at javax.security.auth.Subject.doAs(Subject.java:356)
      at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:522)
      at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:546)
      at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1423)
      at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1500(CommandRunnerImpl.java:108)
      at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1762)
      at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1674)
      at com.sun.enterprise.v3.admin.AdminAdapter.doCommand(AdminAdapter.java:534)
      at com.sun.enterprise.v3.admin.AdminAdapter.onMissingResource(AdminAdapter.java:224)
      at org.glassfish.grizzly.http.server.StaticHttpHandler.service(StaticHttpHandler.java:297)
      at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:246)
      at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:191)
      at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:168)
      at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:189)
      at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
      at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:288)
      at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:206)
      at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:136)
      at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:114)
      at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
      at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:838)
      at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:113)
      at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:115)
      at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:55)
      at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:135)
      at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:564)
      at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:544)
      at java.lang.Thread.run(Thread.java:744)
Caused by: javax.enterprise.concurrent.AbortedException: Module glassfish-executor-test is disabled
      at org.glassfish.enterprise.concurrent.internal.ManagedFutureTask.run(ManagedFutureTask.java:146)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
      at java.lang.Thread.run(Thread.java:744)
```

And the submitted task is not run. (glassfish-executor-test is just the name of the standalone test case that I created).

Surely either the executor service should be initialized and available by the time <tt>@PostConstruct</tt> stuff is executed, or it should queue submitted tasks and execute them once the application is started.

This is just using the default managed executor service in a default <tt>domain.xml</tt> file.
#### Environment
Glassfish 4.0, Java 7, currently testing on Windows 7
#### Affected Versions
[4.0]

### PR DESCRIPTION
**Pull request by OndroMih**
Adds tests for https://github.com/eclipse-ee4j/glassfish/pull/24544.

This PR was previously raised to fix https://github.com/eclipse-ee4j/glassfish/issues/21087 but then this was fixed by https://github.com/eclipse-ee4j/glassfish/pull/24544. What remains in this PR is tests to verify the expected behavior.

### CODE REVIEW

**Comment by OndroMih** [comment]
The failed test ProgressStatusComplexITest doesn't seem to be related to my changes. Can you please check, @dmatej or restart the build?

**Comment by dmatej** [comment]
> The failed test ProgressStatusComplexITest doesn't seem to be related to my changes. Can you please check, @dmatej or restart the build?

3 failures are weird, does it pass locally?
`mvn clean install -T4C -Pfastest && mvn clean install -pl :admin-tests,:application-tests`

File: appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java [hunk 1]
```diff
@@ -250,14 +250,14 @@ private ComponentInvocation getSavedInvocation() {
      */
     private boolean isApplicationEnabled(String appId) {
         if (appId == null) {
-            // we don't know the application name yet, it is starting.
-            return true;
+            return false;
```
Comment (dmatej) [inline appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java:253]: This change is wrong - the DOL does still some magic. I think I did something similar when I reintroduced concurrency before JEE10 and I broke some other things by this change. I see also my FIXME in the history:
```
             // we don't know the application name yet, it is starting.
            // FIXME: it would be good to know the application name even in this phase.
```
You moved the comment down, now it even doesn't make sense, because you return true instead original false.
And  javadoc doesn't make sense too - no exception would be thrown, it would return false. Now it returns true.

Comment (dmatej) [reply appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java:253]: If it all would be written correctly, for null appId it should thrown NPE. We have to get there some day :-)

Comment (OndroMih) [reply appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java:253]: Returning true at the end makes sende - it we have appName but the Application object isn’t created yet, then the app is being deployed and thus it’s enabled. This actually fixes #21087 and it’s a similar fix to how Payara fixed the same issue a while ago.

Comment (OndroMih) [reply appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java:253]: I don’t understand why DOL would call this method with no app name. Then which app is enabled if we return true?

**Comment by OndroMih** [comment]
I ran the whole test suite at night, including the tck, with `mvn install -Ptck`. I had a few failures, I'm investigating them now. So far, I investigated some failures in the `admin-tests` module, and all were related to this issue:

```
java.lang.NoClassDefFoundError: Could not initialize class org.glassfish.exousia.modules.locked.SimplePolicyConfiguration
```

I sporadically see this error also when I start GlassFish manually, it happens to me maybe 1 out of 100 times. When I restart GlassFish it's fixed. Probably some race condition during startup.

File: appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java (hunk 1 above)
Comment (OndroMih) [reply appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java:253]: > This change is wrong - the DOL does still some magic. I think I did something similar when I reintroduced concurrency before JEE10 and I broke some other things by this change.

Now I see that a test in `application-tests` failed exactly because `appName` is `null` in ContextSetupProviderimpl (in concurrent-impl). Because `invocation.getAppName()` is null. I'll try to find out why that happens.

Comment (OndroMih) [reply appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java:253]: Here's the reason for `invocation.getAppName() == null`:
https://github.com/eclipse-ee4j/glassfish/blob/master/appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java#L243

By default, no information from the current invocation is saved for a new thread if JNDI isn't propagated. getSavedInvocation() method either returns an empty invocation (if JNDI should be cleared), or `null` (by defualt). Both are later interpreted as `appName == null`.

I believe that in both cases, a new invocation should be created and some non-JNDI data should be copied, e.g. app name.

Comment (OndroMih) [reply appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java]: OK, I resign for now. I reverted this change. I have an idea how to improve the current concurrency runtime and propagate app context if there's no current context but that would be for another PR.

Comment (OndroMih) [reply appserver/concurrent/concurrent-impl/src/main/java/org/glassfish/concurrent/runtime/ContextSetupProviderImpl.java]: Here's my idea how to propagate app context if there's none set up: https://github.com/eclipse-ee4j/glassfish/pull/24544

**Review by arjantijms — APPROVED** [review]

**Comment by dmatej** [comment]
> DetachAttachITest.uptimePeriodically:65 » NumberFormat For input string: "Up 1 mins 36 secs"

This should not happen, you should receive a job id, not the result. Wasn't it caused by your local changes?
