### PR TITLE
Expose services with local parent locator scope (e.g. @RunLevel) to the service locator in system apps

### LINKED ISSUE #25465: Broken View JMS Physical Destination Statistics
### GlassFish Version (and build number)

7.0.0-7.0.23+

### JDK version

11

### OS

GNU/Linux

### Database

_No response_

### Problem Description

Admin GUI -> server ->  JMS Physical Destination -> Statistics -> View does not work.

With 7.0.23 because:
Image
```
[2025-04-17T10:52:36.337596+02:00] [GF 7.0.23] [INFO] [] [org.glassfish.admingui] [tid: _ThreadID=62 _ThreadName=admin-listener(5)] [levelValue: 800] [[
  Exception Occurred :A MultiException has 2 exceptions.  They are:
1. java.lang.IllegalStateException: Could not find an active context for org.glassfish.hk2.runlevel.RunLevel
2. java.lang.IllegalStateException: While attempting to create a service for SystemDescriptor(
  implementation=com.sun.enterprise.connectors.jms.system.JmsProviderLifecycle
  contracts={com.sun.enterprise.connectors.jms.system.JmsProviderLifecycle}
  scope=org.glassfish.hk2.runlevel.RunLevel
  qualifiers={}
  descriptorType=CLASS
  descriptorVisibility=NORMAL
  metadata=runLevelValue={20},runLevelMode={0},Bundle-SymbolicName={org.glassfish.main.jms.core},Bundle-Version={7.0.23}
  rank=0
  loader=OsgiPopulatorPostProcessor.HK2Loader(OSGiModuleImpl:: Bundle = [org.glassfish.main.jms.core [108]], State = [READY],1496022235)
  proxiable=null
  proxyForSameScope=null
  analysisName=null
  id=1204
  locatorId=0
  identityHashCode=1443194318
  reified=true) in scope org.glassfish.hk2.runlevel.RunLevel an error occured while locating the context
]]
```

With 7.0.0 (up to 7.0.15) because:
Image

### Steps to reproduce

Open Admin GUI and navigate to: server -> JMS Physical Destination. Select **View** for any destination from **Statistics** column.

### Impact of Issue

I'd expect something like in 6.2.5

Image

### LINKED ISSUE #25467: Missing active context for `org.glassfish.hk2.runlevel.RunLevel` in Admin GUI App
### Description

https://github.com/eclipse-ee4j/glassfish/blob/c19cd4cedfb787415dc86e3121ed7edac6dddaa0/appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebModuleListener.java#L279-L284

`defaultServices` seems to contain

```
org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext
org.glassfish.hk2.runlevel.internal.RunLevelControllerImpl
org.glassfish.hk2.runlevel.RunLevelContext
```

which later are not present in `webAppServices` in l. 283.

- This happened after 94ae8aa32adefde8b69d4eac43d7e03b88403e28 (#24898).

### PR DESCRIPTION
**Pull request by OndroMih**
Fixes #25467.
Fixes #25465.

This PR changes the locator of system apps so that it falls back to the parent locator and retrieves services from it directly and not only indirectly via the child locator. The new combining locator searches for services first in the child locator as before, but then delegates to the parent locator directly. This allows retrieving services local to the parent locator, as it was happening before when the parent locator was used as the locator for web apps.

With the change in https://github.com/eclipse-ee4j/glassfish/pull/24898 we introduced a child HK2 locator in webapps, delegating to the previous locator as the parent locator. This was later changed to do this only for system apps (needed for Admin Console) because there were some issues with combining child and parent locator with Faces in Embedded GlassFish.

After that change, the locator doesn't have access to services with scope local to the parent locator, e.g. with the `@RunLevel` scope. Some of these services are accessed directly by Admin Console, e.g. `JmsProviderLifecycle` as described in #25465. Which now results in an exception because the service doesn't have a context in the child locator.

This fix avoids that by asking the parent locator directly if a services is not found or doesn't have a proper context in the child locator.

### CODE REVIEW

File: appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebModuleListener.java [hunk 1]
```diff
@@ -276,13 +277,16 @@ private void configureJsp(WebModule webModule) {
 
     }
 
+    ServiceLocator webAppServices;
```
Comment (pzygielo) [inline appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebModuleListener.java:280]: What is this field used for?

Comment (OndroMih) [reply appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebModuleListener.java:280]: A left-over :)

File: appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebModuleListener.java [hunk 2]
```diff
@@ -276,13 +277,16 @@ private void configureJsp(WebModule webModule) {
...
+
```
Comment (OndroMih) [inline appserver/web/web-glue/src/main/java/com/sun/enterprise/web/WebModuleListener.java:281]:
```suggestion
```

**Review by dmatej — APPROVED** [review]
