### PR TITLE
Classloader security - the fixed package.policy parameter

### LINKED ISSUE #24245: The package.definition property cannot work
When @hs536 noticed my dumb mistake in #24243 , we have found that the property is set via Security.setProperty, but CL parses it from System.getProperty.
As @pzygielo  correctly encouraged, I am creating this issue to fix it.

Usages (based on the mentioned PR)
image

### PR DESCRIPTION
**Pull request by dmatej**
* The setter - Catalina parses and sets the property to the Security.setProperty, then originally WebappCl parsed this property (from wrong class, System). I have connected them together this way; I expect that Catalina configures the property (via it's constructor) before any creation of the WebappCL.
* Fixes #24245 
* Depends on #24243 
* I tried to compare files in history and it seems to me that it was always broken ... but I may be wrong. 
* Despite the first commit fixed the setting in WebappClassLoader, the feature still did not work.
* The second commit added some logs and then I was able to follow what is happening and fix the behavior.
* Then failed six QuickLook tests, because the server chose a secured path which was broken (see reflections in the `ApplicationContextFacade`)

### CODE REVIEW

**Comment by dmatej** [comment]
It is more complicated:

- Catalina loads catalina.properties which contains just an empty string
- Copies all content to the System.properties 
- CatalinaProperties is still in a state rather for Tomcat, should be updated for GlassFish, ie. use domain.xml, not catalina.properties which do not exist, therefore can be loaded from user's home.
  -  catalina.config sysprop is not set in GF.
  - catalina.home is set by Embedded.initDirs, but who knows how and if it is called on GF ...
  - if it is not set, it can use even catalina.properties from user's home
  - Perhaps to be refactored in some future PR, including removal of unused code.
- The issue is that part of the code is static, so when I added logs now, the package protection was ALWAYS disabled. Seems the static initialization in SecurityUtil was too fast.

Therefore at this moment this PR did not change anything. Locally, after some changes, I was able to enable it. Surprisingly the jacc tests passed again.

**Comment by dmatej** [comment]
Ok, I did it, these are defaults on JDK17 :-)
```
[2023-01-20T19:06:46.932525+01:00] [GlassFish 7.0] [FINE] [] [jdk.event.security] [tid: _ThreadID=119 _ThreadName=AutoDeployer] [levelValue: 500] [[
SecurityPropertyModification: key:package.definition, value:sun.misc.,sun.reflect.,]]

[2023-01-20T19:06:46.932614+01:00] [GlassFish 7.0] [CONFIG] [] [jakarta.enterprise.web.core] [tid: _ThreadID=119 _ThreadName=AutoDeployer] [levelValue: 700] [[
appendSecurityProperty(property=package.access, packageList=)]]

[2023-01-20T19:06:46.932750+01:00] [GlassFish 7.0] [FINE] [] [jdk.event.security] [tid: _ThreadID=119 _ThreadName=AutoDeployer] [levelValue: 500] [[
SecurityPropertyModification: key:package.access, value:sun.misc.,sun.reflect.,]]
```

**Comment by dmatej** [comment]
Not sure if this issue is the same in Payara, but I would recommend to check your code too, @smillidge . 

Basically just do a fulltext seach of the `package.definition` and `package.access` strings and look where and when it is set to/from Security.setProperty/getProperty and System.setProperty/getProperty. The result depends on the order of actions which was wrong in GlassFish. When you add and enable logs like we have in GF, run QuickLook tests and look into the server.log, it should be visible.

File: appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java [hunk 1]
```diff
@@ -341,6 +333,20 @@ public void setAntiJARLocking(boolean enable) {
     }
 
 
+    /**
+     * Enables checks for the package definition permissions.
+     *
+     * @param enable
+     */
+    public void setPackageDefinitionSecurityEnabled(boolean enable) {
+        if (enable && SECURITY_MANAGER == null) {
```
Comment (arjantijms) [inline appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java:342]: Note that eventually we'd have to remove all uses of the security manager

**Review by arjantijms — APPROVED** [review]

File: appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java (hunk 1 above)
Comment (dmatej) [reply appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java:342]: Correct, but while it is there, it should work :-)
