### PR TITLE
Fixes #23483 Add lock, add notifyWaitingThreads call for better max pool size logic.

### LINKED ISSUE #23483: It didn't reach the limit of max-pool-size, but there was an maxPoolSize exhausted exception
Hi!

We hava an application that uses jdbc connection pooling.And uses the following settings:
max-pool-size:200
pool-resize-quantity:2
max-wait-time-in-millis:5000

It has been working fine for a long time, but recently we get the following exception while trying to concurrently access.

[java.sql.SQLException:Error in allocating a connection. Cause: In-use connections equal max-pool-size and expired max-wait-time. Cannot allocate more connections.]

The number of concurrent requests is 100.
Actually,It didn't exceed the limit of max-pool-size 200.

By analyzing the ConnectionPool code,we find a problem in ConnectionPool#resizePoolAndGetNewResource.

In order to understand the problem simply,suppose uses the following settings:
max-pool-size:10
pool-resize-quantity:1
max-wait-time-in-millis:5000

and,the problem flow is as follows:
1. now there are five connections in the jdbc connection pool and all these connections are in-used

2. one request comes to get connection(by Thread A)

3. because there's still space to create a connection(current connections < max-pool-size),
   Thread A starts to execute the following resizePoolAndGetNewResource. 
   In **1 method create 1 new connection, and add connection to connection pool.  
   
4. thread A  before executing **2 method (take the connection off from connection pool)
   thread B just comes to get connection,and just takes the connection off from connection pool.
   
5. when thread A executes **2 method,the connection was tooken by thread B, returns null.
   and max-wait-time-in-millis is timeout,in **3 method,the error will happen.

[java.sql.SQLException:Error in allocating a connection. Cause: In-use connections equal max-pool-size and expired max-wait-time. Cannot allocate more connections.]

## Environment Details
* GlassFish Version:5.1.0
* JDK version:1.8.0_201
* OS:ALL
* Database:ALL

## Questions about this case
Now,we hava one question:

When a thread execute the resizePoolAndGetNewResource, should this thread get the connection first?  
If YES,the code of resizePoolAndGetNewResource has a bug.
If NO,the error message [Cause: In-use connections equal max-pool-size and expired max-wait-time.] is not right.

## Related source
com.sun.enterprise.resource.pool.ConnectionPool
```
	private ResourceHandle resizePoolAndGetNewResource(ResourceAllocator alloc) throws PoolingException {
        //Must be called from the thread holding the lock to this pool.
        ResourceHandle result = null;
        int numOfConnsToCreate = 0;
        if (ds.getResourcesSize() < steadyPoolSize) {
            // May be all invalid resources are destroyed as
            // a result no free resource found and no. of resources is less than steady-pool-size
            numOfConnsToCreate = steadyPoolSize - ds.getResourcesSize();
        } else if (ds.getResourcesSize() + resizeQuantity <= maxPoolSize) {
            //Create and add resources of quantity "resizeQuantity"
            numOfConnsToCreate = resizeQuantity;
        } else if (ds.getResourcesSize() < maxPoolSize) {
            // This else if "test condition" is not needed. Just to be safe.
            // still few more connections (less than "resizeQuantity" and to reach the count of maxPoolSize)
            // can be added
            numOfConnsToCreate = maxPoolSize - ds.getResourcesSize();
        }
        if (numOfConnsToCreate > 0) {
             createResources(alloc, numOfConnsToCreate); **1
             result = getMatchedResourceFromPool(alloc); **2
        } else if (ds.getFreeListSize() > 0) {
            //pool cannot create more connections as it is at max-pool-size.
            //If there are free resources at max-pool-size, then none of the free resources
            //has matched this allocator's request (credential). Hence purge free resources
            //of size <=resizeQuantity
            if (purgeResources(resizeQuantity) > 0) {
                result = resizePoolAndGetNewResource(alloc);
            }
        }
        return result;
    }

    public ResourceHandle getResource(ResourceSpec spec, ResourceAllocator alloc, Transaction txn)
            throws PoolingException, RetryableUnavailableException  {
        //Note: this method should not be synchronized or the
        //      startTime would be incorrect for threads waiting to enter

       /*
        * Here are all the comments for the method put together for
        * easy reference.
        *  1.
           // - Try to get a free resource. Note: internalGetResource()
           // will create a new resource if none is free and the max has
           // not been reached.
           // - If can't get one, get on the wait queue.
           // - Repeat this until maxWaitTime expires.
           // - If maxWaitTime == 0, repeat indefinitely.

           2.
           //the doFailAllConnectionsProcessing method would already
           //have been invoked by now.
           //We simply go ahead and create a new resource here
           //from the allocator that we have and adjust the resources
           //list accordingly so as to not exceed the maxPoolSize ever
           //(i.e if steadyPoolSize == maxPoolSize )
           ///Also since we are creating the resource out of the allocator
           //that we came into this method with, we need not worry about
           //matching
        */
        ResourceHandle result = null;

        long startTime = System.currentTimeMillis();
        long elapsedWaitTime;
        long remainingWaitTime = 0;

        while (true) {
            if (gateway.allowed()) {
                //See comment #1 above
                JavaEETransaction jtx = ((JavaEETransaction) txn);
                Set resourcesSet = null;
                if(jtx != null){
	                resourcesSet = jtx.getResources(poolInfo);
		        }
                //allow when the pool is not blocked or at-least one resource is
                //already obtained in the current transaction.
                if (!blocked || (resourcesSet != null && resourcesSet.size() > 0)) {
                    try {
                        result = internalGetResource(spec, alloc, txn);
                    } finally {
                        gateway.acquiredResource();
                    }
                }
            }
            if (result != null) {
                // got one, return it
                if (poolLifeCycleListener != null) {
                    poolLifeCycleListener.connectionAcquired(result.getId());
                    elapsedWaitTime = System.currentTimeMillis() - startTime;
                    poolLifeCycleListener.connectionRequestServed(elapsedWaitTime);
                    if (_logger.isLoggable( Level.FINE) ) {
                        _logger.log(Level.FINE, "Resource Pool: elapsed time " +
                                "(ms) to get connection for [" + spec + "] : " +
                                elapsedWaitTime);
                    }
                }
                //got one - seems we are not doing validation or matching
                //return it
                break;
            } else {
                // did not get a resource.
                if (maxWaitTime > 0) {
                    elapsedWaitTime = System.currentTimeMillis() - startTime;
                    if (elapsedWaitTime < maxWaitTime) {
                        // time has not expired, determine remaining wait time.
                        remainingWaitTime = maxWaitTime - elapsedWaitTime;
                    } else {
                        if (!blocked) {
                            // wait time has expired
                            if (poolLifeCycleListener != null) {
                                poolLifeCycleListener.connectionTimedOut();
                            }
                            String msg = localStrings.getStringWithDefault(
                                    "poolmgr.no.available.resource",
                                    "No available resource. Wait-time expired.");
                            ** throw new PoolingException(msg); **3
                        }
                    }
                }
```

### PR DESCRIPTION
**Pull request by escay**
Fixes #23483 Add lock logic between 2 methods, add notifyWaitingThreads call for better max pool size logic.

Add lock, add notifyWaitingThreads call for better max pool size logic. No longer getResources while the pool is being resized. And inform waiting threads when resources are marked as failed. 

See my analysis in #23483 for more information. Short version: getResource takes a connection from the pool, and resizes the pool when needed, while in the meantime another thread returns a resource to the pool, causing the resizePoolAndGetNewResource method to make the pool size too large. And in case of failing connections are being returned, the waiting threads are not informed, while they could ask for a fresh new connection from the pool.

Without the changes in ConnectionPool you should be able to reproduce the issues with the unit test. It might be needed to run the test several times, or increase the number of tasks in the test itself.

### CODE REVIEW

File: appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/ConnectionPool.java [hunk 1]
```diff
@@ -67,38 +68,136 @@ public class ConnectionPool implements ResourcePool, ConnectionLeakListener, Res
     private static final Logger LOG = LogDomains.getLogger(ConnectionPool.class, LogDomains.RSR_LOGGER);
 
     // pool life-cycle config properties
+    /**
+     * Represents the "max-wait-time-in-millis" configuration value.<br>
```
Comment (pzygielo) [inline appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/ConnectionPool.java:72]: I guess it's about different config val.

Comment (escay) [reply appserver/connectors/connectors-runtime/src/main/java/com/sun/enterprise/resource/pool/ConnectionPool.java]: Fixed in commit [9208483](https://github.com/eclipse-ee4j/glassfish/pull/24879/commits/92084835a8cd6365a37910d96ee4d435e473e3ab)

**Review by dmatej — APPROVED** [review]

**Review by pzygielo — APPROVED** [review]
